# Generated by Django 3.0.8 on 2020-07-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushes',
            name='picture',
            field=models.URLField(help_text='Пример: https://yourapp.com/image.png', verbose_name='Изображение уведомления'),
        ),
    ]
